kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    repo: tkvba/HarnessDrone
  when:
    event:
    - pull_request
    - push

- name: push
  image: plugins/docker
  settings:
    username: u_docker
    password: p_docker
      from_secret: dockerhubpw
    repo: sndjnky/tk
    tag:
    - latest
    - ${DOCKER_TAG}
  when:
    event:
    - custom
